### ISSUE TITLE
[WIP] Requirements {gathering}

### ISSUE THREAD

**Issue by Asshes** [makerspacelt/pim#1]
Home Page
- Search 
- Categories [grid?]
- Tags

Category Page
- Filter [by subcategory, technical stuff]
- Items [grid/list] 
- Tags

Subcategory Page
- Do we need this?

Item Page
- Barcode [requirements for barcode will follow]
- Title
- Photo [more than one]
- Description / Technical information
- Original price
- Service log
- Tags

Search Results Page
- ?

----------------

Physical Barcodes/QR Codes

**Comment by aivarasbaranauskas** [comment]
"Search Results Page" - grid too. Consistency!
